### ISSUE TITLE
安装规则包时出现异常

### ISSUE THREAD

**Issue by BegoniaHe** [noctisynth/noctisdice#1]
可恶，出现了一些小问题，检查规则包出现异常
系统环境：win11 22h2
python3.12.2
<img width="847" alt="Image_1712542197217" src="https://github.com/noctisynth/noctisdice/assets/163421589/8c5a473d-7778-44e5-9ebe-faa644f9f454">

**Comment by fu050409** [comment]
这是一个网络问题，接下来会在`ipdm`侧对哈希验证进行优化，请检查网络连接

世界树主站使用 Cloudflare 托管，部分网络环境下可能导致数据传输失败或不完全，接下来我们可能会尝试使用和华为侧开源社区提供的 Gitcode Pages 进行托管

**Comment by fu050409** [comment]
此问题会在 https://github.com/noctisynth/yggdrasil/issues/2 进行处理，此 issue 将关闭。
